### ISSUE TITLE
A Problem in R16

### ISSUE THREAD

**Issue by chenguangtu** [franciscofranco/one_plus_3T#3]
it seems the kernel can not block the wakelock like timefd,wlan,NETLINK during screen off.My kernel version is r16 OP3

**Comment by dorimanx** [comment]
take a look here.
https://forum.xda-developers.com/showpost.php?p=71605487&postcount=2106
You should try to understand about what you report.

**Comment by chenguangtu** [comment]
@dorimanx Thanks
